import{a as d,S as q,i as l}from"./assets/vendor-C1DvvBV_.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function r(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(e){if(e.ep)return;e.ep=!0;const o=r(e);fetch(e.href,o)}})();d.defaults.baseURL="https://pixabay.com/api/";d.defaults.params={key:"57618791-4db8b96e533d358f5552878ee",image_type:"photo",orientation:"horizontal",safesearch:!0};const f=15;async function m(s,t){return(await d.get("",{params:{q:s,page:t,per_page:f}})).data}const g=document.querySelector(".loader"),y=document.querySelector(".load-more"),h=document.querySelector(".gallery"),v=new q(".gallery a");function p(){g.classList.remove("is-hidden")}function L(){g.classList.add("is-hidden")}function M(){y.classList.remove("is-hidden")}function u(){y.classList.add("is-hidden")}const w=function(t){const r=t.map(({webformatURL:n,largeImageURL:e,tags:o,likes:i,views:E,comments:O,downloads:P})=>`<li class='gallery-item'>
       <a href = '${e}'>
       <img src = '${n}' alt = '${o}'/>
       </a>
       <ul class ='info'>
         <li class="info-item">Likes <span class="span-info">${i}</span></li>
         <li class="info-item">Views <span class="span-info">${E}</span></li>
         <li class="info-item">Comments <span class="span-info">${O}</span></li>
         <li class="info-item">Downloads <span class="span-info">${P}</span></li>
       </ul>
   </li>`).join("");h.insertAdjacentHTML("beforeend",r),v.refresh()},$=function(){h.innerHTML=""};let c="",a=1;const b=document.querySelector(".form");b.addEventListener("submit",G);const B=document.querySelector(".load-more");B.addEventListener("click",x);async function x(){a+=1,p(),u();try{const{hits:s,totalHits:t}=await m(c,a);w(s),S(a,t);const r=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}catch(s){console.error(s.message),l.error({title:"Error",message:"Oops! Something went wrong while loading images. Please try again later."})}finally{L()}}async function G(s){s.preventDefault();const t=new FormData(s.target).get("search-text").trim();if(t===""){l.error({title:"Error",message:"Заповніть поле вводу"});return}c=t,a=1,$(),p(),u();try{const{hits:r,totalHits:n}=await m(c,a);r.length===0?l.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"}):(b.reset(),w(r),S(a,n))}catch(r){console.error(r.message),l.error({title:"Error",message:"Oops! Something went wrong while loading images. Please try again later."})}finally{L()}}const S=function(t,r){t*f>=r?(u(),l.info({title:"Info",message:"We're sorry, but you've reached the end of search results."})):M()};
//# sourceMappingURL=index.js.map
