import{a as u,S as v,i as c}from"./assets/vendor-C1DvvBV_.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function r(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(e){if(e.ep)return;e.ep=!0;const o=r(e);fetch(e.href,o)}})();u.defaults.baseURL="https://pixabay.com/api/";u.defaults.params={key:"57618791-4db8b96e533d358f5552878ee",image_type:"photo",orientation:"horizontal",safesearch:!0};async function d(s,t){return(await u.get("",{params:{q:s,page:t,per_page:15}})).data}const f=document.querySelector(".loader"),m=document.querySelector(".load-more"),y=document.querySelector(".gallery"),M=new v(".gallery a");function h(){f.classList.remove("is-hidden")}function p(){f.classList.add("is-hidden")}function O(){m.classList.remove("is-hidden")}function $(){m.classList.add("is-hidden")}const g=function(t){const r=t.map(({webformatURL:n,largeImageURL:e,tags:o,likes:i,views:w,comments:S,downloads:q})=>`<li class='gallery-item'>
       <a href = '${e}'>
       <img src = '${n}' alt = '${o}'/>
       </a>
       <ul class ='info'>
         <li class="info-item">Likes <span class="span-info">${i}</span></li>
         <li class="info-item">Views <span class="span-info">${w}</span></li>
         <li class="info-item">Comments <span class="span-info">${S}</span></li>
         <li class="info-item">Downloads <span class="span-info">${q}</span></li>
       </ul>
   </li>`).join("");y.insertAdjacentHTML("beforeend",r),M.refresh()},B=function(){y.innerHTML=""},L=function(t,r){t*15>=r?($(),c.info({title:"Info",message:"We're sorry, but you've reached the end of search results."})):O()};let l="",a=1;const b=document.querySelector(".form");b.addEventListener("submit",x);const E=document.querySelector(".load-more");E.addEventListener("click",P);async function P(){a+=1,h();try{const{hits:s,totalHits:t}=await d(l,a);g(s),L(a,t);const r=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}catch(s){console.error(s.message)}finally{p()}}async function x(s){s.preventDefault();const t=new FormData(s.target).get("search-text").trim();if(t===""){c.error({title:"Error",message:"Заповніть поле вводу"});return}l=t,a=1,B(),h();try{const{hits:r,totalHits:n}=await d(l,a);r.length===0?c.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"}):(b.reset(),g(r),L(a,n))}catch(r){console.error(r.message)}finally{p()}}
//# sourceMappingURL=index.js.map
